python script/test-onset.py test \
--config "/path/to/logs/folder/onset/train-augment/config.yaml" \
--ckpt_path "/path/to/logs/folder/onset/checkpoints-augment/last.ckpt" \
--trainer.logger.save_dir "/path/to/logs/folder/onset/test-augment/last" \
--trainer.logger.entity team-mcomunita \
--trainer.logger.project diffusion-sfx \
--trainer.logger.name GH-test-augment-last-0.75thresh \
--trainer.logger.group ONSET-TEST \
--trainer.accelerator gpu \
--trainer.strategy auto \
--trainer.devices=1 \
--data.test_data_to_use 1.0
